PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX requirement: <https://fireforce6.github.io/sierra/requirement#>
PREFIX capability: <https://fireforce6.github.io/sierra/capability#>

PREFIX base: <https://fireforce6.github.io/sierra/base#>

SELECT DISTINCT ?requirementURI ?requirementDescription ?requirementExpression ?capabilityURI ?capabilityDescription ?subCapabilityURI ?subCapabilityDescription

WHERE {
	?requirementURI a requirement:Requirement ;
	base:expression ?requirementExpression ;
	base:description ?requirementDescription .

	?capabilityURI a capability:Capability ;
	base:description ?capabilityDescription ;
	capability:isDerivedFrom ?requirementURI;

	OPTIONAL {
		?capabilityURI capability:requires ?subCapabilityURI .
		?subCapabilityURI base:description ?subCapabilityDescription
	}
}